### ISSUE TITLE
Emojitwo

### ISSUE THREAD

**Issue by Crissov** [maximbaz/docker-joypixels-fonts-build#1]
I don’t have much experience with Travis and none with [Docker](https://github.com/emojione/emojione-assets/pull/30). Should this work straight away with [Emojitwo](https://GitHub.com/EmojiTwo/emojitwo/) as well? The file and directory names should be the same as in emojione-assets. Do I need to keep some metadata files up to date?

**Comment by max-baz** [comment]
The build process itself is likely to work for Emojitwo, but we need to solve some issues first. These are the issues that I discovered by trying to build the Emojitwo font:

- The folder structure in emojitwo is different from emojione-assets. The code now expects to find pictures in the location "repo/png/128/\*.png", while in emojitwo the location is "repo/png_128x128/\*.png". We could detect this in code and move files around, but it would make life and future code maintenance simpler if the folder structure is identical among two repositories - would it be possible for you to align folder structure with emojione-assets?
- I adjusted the folder structure locally and proceeded with the build. Next issue is that the structure of "emojitwo/emoji.json" differs from the structure of "emojione-assets/emoji.json". First of all, the keys are the unicode codes (e.g. "1f600") in emojione-assets, but are human-friendly names (e.g. "grinning") in emojitwo - this breaks the script that parses this file. What is the script doing - the script has to rename files in order to correctly build the font file (see for details: https://github.com/emojione/emojione-assets/issues/24). A certain metadata (`non_fully_qualified` property for every glyph) was added recently in "emojione-assets/emoji.json", it is critical that the "emojitwo/emoji.json" also contains this metadata.
- I tried to simply use the "emoji.json" from emojione-assets, however it seems to be incompatible with emojitwo. The build script stops at the first error, saying that emojitwo has a png file "2624.png", but "emojione-assets/emoji.json" doesn't have metadata for this image (emojione doesn't seem to have this image in general).

If you could solve these issues, I could give it another go at building the font.

**Comment by Crissov** [comment]
Thank you for this analysis. I can change the PNG folder structure, I guess, since nothing and nobody relies on the current one as far as I know. The JSON is indeed mostly the old one from Emojione 2.2 which has been changed for version 3.x. I plan to update it soon and also document the characters that have been added to Emojitwo. This will probably take several days or weeks, though.

**Comment by max-baz** [comment]
All right, just ping me when you make the changes, and I'll try again 👍

**Comment by Crissov** [comment]
I have updated the JSON file. It would be swell if you could test again.

**Comment by max-baz** [comment]
I can see that not all emoji descriptions in "emoji.json" have the "non_fully_qualified" property among its code_points - but it is essential to have it. Could you please add them?

Example:

```
	"263a": {
		"code_points": {
			"base": "263a",
			"alt": "263a-fe0f",
			"decimal": "&#9786;"
		},
```

There is 1999 definitions of "code_points" in the file, but only 1727 definitions of "non_fully_qualified" property.

**Comment by Crissov** [comment]
Oops, sorry, I thought I had fixed that, should be now.

**Comment by max-baz** [comment]
Now the following images don't have their metadata in emoji.json:

```
No metadata for image file '0023' in '/assets/emoji.json'
No metadata for image file '0035' in '/assets/emoji.json'
No metadata for image file '0039' in '/assets/emoji.json'
No metadata for image file '0034' in '/assets/emoji.json'
No metadata for image file '0033' in '/assets/emoji.json'
No metadata for image file '0032' in '/assets/emoji.json'
No metadata for image file '0030' in '/assets/emoji.json'
No metadata for image file '0031' in '/assets/emoji.json'
No metadata for image file '1f6ea' in '/assets/emoji.json'
No metadata for image file '0036' in '/assets/emoji.json'
No metadata for image file '2765' in '/assets/emoji.json'
No metadata for image file '002a' in '/assets/emoji.json'
No metadata for image file '0038' in '/assets/emoji.json'
No metadata for image file '0037' in '/assets/emoji.json'
There was an error while renaming images, aborting.
```

In other words, they exist as png files, but are not defined in emoji.json

**Comment by Crissov** [comment]
Hm. I seem to have missed 2765 and 1f6ea, the Latin-0 chars should have been there from Emojione. Have added them now.

**Comment by max-baz** [comment]
The font is compiling now 🎉 Could you test it? I tested a bit, basic emojis seem to work, however complex emojis like "woman golfing" or "woman astronaut" don't - are they supposed to work in EmojiTwo?

[emojitwo-android.zip](https://github.com/maximbaz/docker-emojione-fonts-build/files/1218464/emojitwo-android.zip)

In any case, to make the font compile automatically in EmojiTwo repo, follow exactly the same steps as in this PR (and take `.travis.yml` from there): https://github.com/emojione/emojione-assets/pull/30

If you want the file to be called "emojitwo-android.ttf" instead of "emojione-android.ttf", do the following adjustments to the `.travis.yml` file:

1. Line 26, replace "emojione-android.ttf" with "emojitwo-android.ttf"
2. After line 17, add a second step after `docker run`:

```
  - mv "$FONTS_DIR/emojione-android.ttf" "$FONTS_DIR/emojitwo-android.ttf"
```

The font will be compiled on every commit, but when you push a new tag on github, the compiled font will also be automatically attached to it.

**Comment by Crissov** [comment]
Yay, thank you so much! 

Emojitwo does not support most of Emoji 4.0+ yet, i.e. it's to be expected that the gender variants won't work.

**Comment by max-baz** [comment]
Did you manage to configure Travis, as described in https://github.com/emojione/emojione-assets/pull/30? I can see that you created `.travis.yml` and even made some new commits after that, but the font is not being built, so I wonder if you simply haven't got to this yet, or need some assistance? 🙂

**Comment by Crissov** [comment]
I think I have configured Travis to only build upon a branch merge, not on every commit. I didn’t find a button to manually initiate a run.

I’m planning to automate conversion from SVG to PNG. When that is in place, I might change it to build on commit.

**Comment by max-baz** [comment]
Makes sense. All right, enjoy, and ping me if you discover any issue 😉
